// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "pvz/internal/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// ProductService is an autogenerated mock type for the ProductService type
type ProductService struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: typeStr, pvzId
func (_m *ProductService) CreateProduct(typeStr string, pvzId string) (*model.Product, error) {
	ret := _m.Called(typeStr, pvzId)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *model.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.Product, error)); ok {
		return rf(typeStr, pvzId)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.Product); ok {
		r0 = rf(typeStr, pvzId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(typeStr, pvzId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteLastProduct provides a mock function with given fields: pvzID, userRole
func (_m *ProductService) DeleteLastProduct(pvzID string, userRole string) error {
	ret := _m.Called(pvzID, userRole)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLastProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(pvzID, userRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductService creates a new instance of ProductService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductService {
	mock := &ProductService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
