// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	model "pvz/internal/domain/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ReceptionService is an autogenerated mock type for the ReceptionService type
type ReceptionService struct {
	mock.Mock
}

// CloseLastReception provides a mock function with given fields: pvzID
func (_m *ReceptionService) CloseLastReception(pvzID uuid.UUID) (*model.Reception, error) {
	ret := _m.Called(pvzID)

	if len(ret) == 0 {
		panic("no return value specified for CloseLastReception")
	}

	var r0 *model.Reception
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*model.Reception, error)); ok {
		return rf(pvzID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *model.Reception); ok {
		r0 = rf(pvzID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Reception)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(pvzID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartReception provides a mock function with given fields: pvzID
func (_m *ReceptionService) StartReception(pvzID uuid.UUID) (*model.Reception, error) {
	ret := _m.Called(pvzID)

	if len(ret) == 0 {
		panic("no return value specified for StartReception")
	}

	var r0 *model.Reception
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*model.Reception, error)); ok {
		return rf(pvzID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *model.Reception); ok {
		r0 = rf(pvzID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Reception)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(pvzID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReceptionService creates a new instance of ReceptionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReceptionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReceptionService {
	mock := &ReceptionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
